version: '3'
services:
  react:
    build: front/
    container_name: react
    networks:
      - transcendence-network
    ports:
      - 3006:3006
    depends_on:
      - nestjs
    volumes:
      - front:/usr/src/app
      - /usr/src/app/node_modules
    restart: always

  nestjs:
    build: back/
    container_name: nestjs
    networks:
      - transcendence-network
    ports:
      - 3000:3000
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - back:/usr/src/app
      - /usr/src/app/node_modules
    restart: always

  postgres:
    build: db/
    container_name: postgres
    networks:
      - transcendence-network
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - transcendence-network

# ------------------------------------------------------------------------- #
volumes:
  postgres_data:
  pgadmin_data:
  front:
    driver: local
    driver_opts:
      type: none
      device: ${FRONT_VOLUME}
      o: bind
  back:
    driver: local
    driver_opts:
      type: none
      device: ${BACK_VOLUME}
      o: bind


# ------------------------------------------------------------------------- #
networks:
  transcendence-network:
    driver: bridge