version: "3"
services:
  nestjs:
    build:
      context: .
      dockerfile: ./back/docker/Dockerfile
    container_name: nestjs
    ports:
      - 3000:3000
    depends_on:
      - postgres
    restart: always
    environment:
      API_URL: ${HOST_IP_FRONT}

  postgres:
    build: db/
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always

  react:
    build:
      context: ./front
      dockerfile: ./docker/Dockerfile
    container_name: react
    ports:
      - 80:80
    depends_on:
      - nestjs
    volumes:
      - front:/app
      - /app/node_modules
    restart: always
    environment:
      VITE_API_URL: ${HOST_IP_BACK}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"

# ------------------------------------------------------------------------- #
volumes:
  postgres_data:
  pgadmin_data:
  front:
    driver: local
    driver_opts:
      type: none
      device: ${FRONT_VOLUME}
      o: bind
  back:
    driver: local
    driver_opts:
      type: none
      device: ${BACK_VOLUME}
      o: bind

