version: '3'
services:
  nestjs:
    build: back/
    container_name: nestjs
    networks:
      - transcendence-network
    ports:
      - 3000:3000
    depends_on:
      - postgres
    restart: always

  postgres:
    build: postgres
    container_name: postgres
    networks:
      - transcendence-network
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/15/main/
    environment:
      DB_HOST : ${DB_HOST}
      DB_PORT : ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
      - back/.env
    restart: always



# ------------------------------------------------------------------------- #
volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DB}
      o: bind


# ------------------------------------------------------------------------- #
networks:
  transcendence-network:
    driver: bridge