export const trophies = [
  {
    name: 'Beginner',
    description: 'Play your first game',
    imagePath: 'beginner.jpeg',
  },
  {
    name: 'Warrior',
    description: 'Win 3 games in a row',
    imagePath: 'warrior.jpeg',
    total: 3,
  },
  {
    name: 'Lord',
    description: 'Win 5 games in a row',
    imagePath: 'lord.jpeg',
    progress: 0,
    total: 5,
  },
  {
    name: 'Emperor',
    description: 'Win 10 games in a row',
    imagePath: 'emperor.jpeg',
    progress: 0,
    total: 10,
  },
  {
    name: 'Laser Pointer',
    description: 'Kill an opponent with a Laser',
    imagePath: 'laser_pointer.jpeg',
  },
  {
    name: 'Gamma Laser',
    description: 'Kill 5 opponents with a laser',
    imagePath: 'gamma_laser.jpeg',
    progress: 0,
    total: 5,
  },
  {
    name: 'Scorificator',
    description: 'Kill 10 opponents with a laser',
    imagePath: 'scorificator.jpeg',
    progress: 0,
    total: 10,
  },
  {
    name: 'Regular',
    description: 'Play 20 games',
    imagePath: 'regular.jpeg',
    progress: 0,
    total: 20,
  },
  {
    name: 'Addict',
    description: 'Play 50 games',
    imagePath: 'addict.jpeg',
    progress: 0,
    total: 50,
  },
  {
    name: 'NoLife',
    description: 'Play 100 games',
    imagePath: 'nolife.jpeg',
    progress: 0,
    total: 100,
  },
  {
    name: 'Bonus Master',
    description: 'Use 3 bonuses in one game',
    imagePath: 'bonus_master.jpeg',
    progress: 0,
    total: 3,
  },
  {
    name: 'Bonus Pro',
    description: 'Use 5 bonuses in one game',
    imagePath: 'bonus_pro.jpeg',
    progress: 0,
    total: 5,
  },
  {
    name: 'Bonus Cheater',
    description: 'Use 10 bonuses in one game',
    imagePath: 'bonus_cheater.jpeg',
    progress: 0,
    total: 10,
  },
  {
    name: 'Pong-tastic',
    description: 'Win 5 games without missing a single ball',
    imagePath: 'pong_tastic.jpeg',
    progress: 0,
    total: 5,
  },
  {
    name: 'Tireless Returner',
    description:
      'Return the ball 10 times in a row without it touching the sides',
    imagePath: 'tireless_returner.jpeg',
    progress: 0,
    total: 10,
  },
  {
    name: 'Why Not',
    description: 'Win a bonus game without using any bonuses',
    imagePath: 'why_not.jpeg',
  },
  {
    name: 'Ping King',
    description: 'Score a point when the ball is at high speed',
    imagePath: 'ping_king.jpeg',
  },
  {
    name: 'Faster Than Light',
    description: 'Score a point when the ball is at maximum speed',
    imagePath: 'faster_than_light.jpeg',
  },
  {
    name: 'Blitz Pong',
    description: 'Win a game in less than 2 minutes',
    imagePath: 'blitz_pong.jpeg',
  },
  {
    name: 'Invincible Resistant',
    description: 'Win a game without losing a single point',
    imagePath: 'invincible_resistant.jpeg',
  },
  {
    name: 'Point Prospector',
    description: 'Win a game with a minimum of 30 points scored',
    imagePath: 'point_prospector.jpeg',
    progress: 0,
    total: 30,
  },
];
